# Generated by Django 5.0.1 on 2024-05-14 06:04

import datetime
import django.db.models.deletion
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('text', models.TextField(max_length=512)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2024, 5, 14, 11, 4, 15, 302505))),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion', models.CharField(max_length=64)),
                ('header', models.CharField(max_length=32)),
                ('text', models.TextField(max_length=512)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2024, 5, 14, 11, 4, 15, 302505))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=50, validators=[users.models.User.mail_validation], verbose_name='Email')),
                ('password', models.CharField(db_index=True, max_length=32, verbose_name='Пароль')),
                ('phone', models.CharField(max_length=12, validators=[users.models.User.number_validation], verbose_name='Номер телефона')),
                ('full_name', models.CharField(max_length=64, verbose_name='Имя Фамилия')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг')),
                ('rating_number', models.IntegerField(blank=True, null=True, verbose_name='Кол-ва рейтингов')),
                ('info', models.CharField(blank=True, max_length=512, null=True, verbose_name='Информация о себе')),
                ('status', models.CharField(choices=[('1', 'Admin'), ('2', 'Guide'), ('3', 'Client')], default=('3', 'Client'), max_length=32, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
