# Generated by Django 5.0.1 on 2024-05-30 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_review_datetime_alter_update_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 11, 6, 25, 376724)),
        ),
        migrations.AlterField(
            model_name='update',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 11, 6, 25, 376724)),
        ),
    ]
