# Generated by Django 5.0.1 on 2024-05-30 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_update_is_review_alter_review_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_past',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 11, 33, 0, 119726)),
        ),
        migrations.AlterField(
            model_name='update',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 11, 33, 0, 119726)),
        ),
    ]
