# Generated by Django 5.0.1 on 2024-06-02 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_review_rating_alter_review_datetime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterField(
            model_name='update',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 17, 23, 54, 797082)),
        ),
    ]
