# Generated by Django 5.0.1 on 2024-06-02 12:24

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_review_alter_update_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 17, 24, 34, 180257)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг')),
                ('text', models.TextField(max_length=512)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2024, 6, 2, 17, 24, 34, 180257))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
