# Generated by Django 5.0.1 on 2024-06-02 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_update_datetime_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 17, 38, 29, 10899)),
        ),
        migrations.AlterField(
            model_name='update',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 17, 38, 29, 10899)),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-ва рейтингов'),
        ),
    ]
