# Generated by Django 5.0.1 on 2024-06-02 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_review_datetime_alter_update_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 21, 7, 12, 345361)),
        ),
        migrations.AlterField(
            model_name='update',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 21, 7, 12, 344364)),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='guide', max_length=32, verbose_name='Статус'),
        ),
    ]
