# Generated by Django 5.0.1 on 2024-05-14 06:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Attraction', max_length=32)),
                ('info', models.CharField(max_length=2048, verbose_name='Информация')),
                ('photo', models.CharField(blank=True, max_length=128)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Excursion', max_length=32)),
                ('info', models.CharField(max_length=2048, verbose_name='Информация')),
                ('type', models.CharField(choices=[('1', 'Индивидуальная'), ('2', 'Групповая')], default=('2', 'Групповая'), max_length=32, verbose_name='Тип экскурсии')),
                ('kind', models.CharField(choices=[('1', 'Культурно-познавательная'), ('2', 'Лечевно-оздоровительная'), ('3', 'Спортивная и экстремальная'), ('4', 'Религиозная'), ('5', 'Природно-заповедные места'), ('6', 'Экотуризм')], default=('2', 'Лечевно-оздоровительная'), max_length=32, verbose_name='Тип экскурсии')),
                ('people_number', models.IntegerField(blank=True)),
                ('time', models.IntegerField(verbose_name='Duration')),
                ('guide', models.CharField(max_length=64)),
                ('transport', models.CharField(choices=[('1', 'Пешком'), ('2', 'Машина'), ('3', 'Автобус')], default=('3', 'Автобус'), max_length=32, verbose_name='Транспорт')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('program', models.CharField(max_length=512, verbose_name='Программа')),
                ('photo', models.CharField(blank=True, max_length=128)),
                ('datetime', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('clients_count', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('is_past', models.BooleanField(default=False)),
                ('attractions', models.ManyToManyField(to='excursions.attraction')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
            ],
        ),
    ]
