# Generated by Django 5.0.1 on 2024-05-30 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_alter_excursion_kind_alter_excursion_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked', models.DateTimeField(default=datetime.datetime(2024, 5, 30, 4, 26, 40, 104466, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='excursion',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
