# Generated by Django 5.0.1 on 2024-05-30 04:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0003_checktimestamp_alter_excursion_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktimestamp',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
