# Generated by Django 5.0.1 on 2024-06-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0004_alter_checktimestamp_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='photo',
            field=models.CharField(default='img/images/no-photo.jpg', max_length=128),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='photo',
            field=models.CharField(default='img/images/no-photo.jpg', max_length=128),
        ),
    ]
